#!/bin/bash
#
# Name:        10-version_hold.sh
# Purpose:     Manage apt-mark holds and apt preference pins as a data-driven
#              operation using a declarative hold registry
# Author:      Nargiz Naghiyeva
# Date:        August 18, 2026
#

set -euo pipefail

readonly SCRIPT_NAME="$(basename "$0")"
readonly BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

readonly REGISTRY_FILE="${BASE_DIR}/hold_registry.json"
readonly PREFS_FILE="/etc/apt/preferences.d/meddefense-pins"
readonly OUTPUT_FILE="${BASE_DIR}/hold_management.json"

log() {
    echo "[*] $*"
}

info() {
    echo "    $*"
}

warn() {
    echo "[!] $*" >&2
}

validate_prerequisites() {
    if [[ ! -f "$REGISTRY_FILE" ]]; then
        warn "Hold registry file not found: $REGISTRY_FILE"
        warn "Create a hold_registry.json file with the required schema."
        exit 1
    fi

    if ! jq empty "$REGISTRY_FILE" 2>/dev/null; then
        warn "Invalid JSON in hold_registry.json"
        exit 1
    fi
}

read_registry() {
    jq '.holds | length' "$REGISTRY_FILE" 2>/dev/null || echo 0
}

get_current_holds() {
    apt-mark showhold 2>/dev/null | sort -u || echo ""
}

compute_days_to_review() {
    local review_date="$1"
    local today
    today=$(date +%Y-%m-%d)

    local review_epoch today_epoch
    review_epoch=$(date -d "$review_date" +%s 2>/dev/null || echo 0)
    today_epoch=$(date -d "$today" +%s 2>/dev/null || echo 0)

    if [[ "$review_epoch" -eq 0 ]]; then
        echo "9999"
        return
    fi

    local diff_seconds=$((review_epoch - today_epoch))
    local diff_days=$((diff_seconds / 86400))
    echo "$diff_days"
}

write_prefs_fragment() {
    mkdir -p "$(dirname "$PREFS_FILE")"
    
    {
        printf "// Auto-generated by 10-version_hold.sh\n"
        printf "// Managed hold pins for MedDefense billing-srv-01\n"
        printf "// Do not edit manually — update hold_registry.json and re-run\n\n"

        while IFS= read -r entry; do
            [[ -z "$entry" ]] && continue

            local pkg pin_version
            pkg=$(echo "$entry" | jq -r '.package')
            pin_version=$(echo "$entry" | jq -r '.pin_version // ""')

            if [[ -n "$pin_version" ]]; then
                printf "Package: %s\nPin: version %s\nPin-Priority: 1001\n\n" "$pkg" "$pin_version"
            else
                printf "Package: %s\nPin: release *\nPin-Priority: 1001\n\n" "$pkg"
            fi
        done < <(jq -c '.holds[]' "$REGISTRY_FILE" 2>/dev/null)
    } > "$PREFS_FILE"

    chmod 644 "$PREFS_FILE"
}

main() {
    validate_prerequisites

    # ============================================
    # STEP 1: Read registry
    # ============================================
    local registry_count
    registry_count=$(read_registry)
    log "Reading hold_registry.json...           (${registry_count} entries)"

    # ============================================
    # STEP 2: Read current holds
    # ============================================
    local current_holds
    current_holds=$(get_current_holds)
    local current_hold_count=0
    if [[ -n "$current_holds" ]]; then
        current_hold_count=$(echo "$current_holds" | grep -c . || true)
    fi
    log "Reading current apt-mark showhold...    (${current_hold_count} entry)"

    # ============================================
    # STEP 3: Build registry package set
    # ============================================
    declare -A registry_packages
    while IFS= read -r entry; do
        [[ -z "$entry" ]] && continue
        local pkg
        pkg=$(echo "$entry" | jq -r '.package')
        registry_packages["$pkg"]=1
    done < <(jq -c '.holds[]' "$REGISTRY_FILE" 2>/dev/null)

    # ============================================
    # STEP 4: Apply holds from registry
    # ============================================
    echo "Applying holds:"

    local applied_temp
    applied_temp=$(mktemp)

    while IFS= read -r entry; do
        [[ -z "$entry" ]] && continue

        local pkg reason owner review_date pin_version
        pkg=$(echo "$entry" | jq -r '.package')
        reason=$(echo "$entry" | jq -r '.reason // ""')
        owner=$(echo "$entry" | jq -r '.owner // ""')
        review_date=$(echo "$entry" | jq -r '.review_date // ""')
        pin_version=$(echo "$entry" | jq -r '.pin_version // ""')

        apt-mark hold "$pkg" >/dev/null 2>&1 || true

        if [[ -n "$pin_version" ]]; then
            printf "  %-23s hold + pin %-20s OK\n" "$pkg" "$pin_version"
        else
            printf "  %-23s hold %-26s OK\n" "$pkg" ""
        fi

        local days_to_review
        days_to_review=$(compute_days_to_review "$review_date")

        jq -nc \
            --arg pkg "$pkg" \
            --arg reason "$reason" \
            --arg owner "$owner" \
            --arg review_date "$review_date" \
            --arg pin_version "$pin_version" \
            --argjson days_to_review "$days_to_review" \
            '{package:$pkg, reason:$reason, owner:$owner, review_date:$review_date, pin_version:$pin_version, days_to_review:$days_to_review}' \
            >> "$applied_temp"

    done < <(jq -c '.holds[]' "$REGISTRY_FILE" 2>/dev/null)

    # ============================================
    # STEP 5: Write apt preferences fragment
    # ============================================
    write_prefs_fragment

    # ============================================
    # STEP 6: Release holds not in registry (convergence mode)
    # ============================================
    echo "Releasing holds no longer in registry:"

    local released_temp
    released_temp=$(mktemp)

    if [[ -n "$current_holds" ]] && [[ "$current_hold_count" -gt 0 ]]; then
        while IFS= read -r held_pkg; do
            [[ -z "$held_pkg" ]] && continue

            if [[ -z "${registry_packages[$held_pkg]:-}" ]]; then
                apt-mark unhold "$held_pkg" >/dev/null 2>&1 || true
                printf "  %s\n" "$held_pkg"
                jq -nc --arg pkg "$held_pkg" '{package:$pkg, action:"released"}' >> "$released_temp"
            fi
        done <<< "$current_holds"
    fi

    local released_count=0
    if [[ -s "$released_temp" ]]; then
        released_count=$(grep -c . "$released_temp" || true)
    fi

    if [[ "$released_count" -eq 0 ]]; then
        echo "  (none)"
    fi

    # ============================================
    # STEP 7: Compute overdue reviews
    # ============================================
    local overdue_temp
    overdue_temp=$(mktemp)

    while IFS= read -r entry; do
        [[ -z "$entry" ]] && continue

        local pkg review_date days_to_review
        pkg=$(echo "$entry" | jq -r '.package')
        review_date=$(echo "$entry" | jq -r '.review_date // ""')
        days_to_review=$(echo "$entry" | jq -r '.days_to_review // 9999')

        if ! [[ "$days_to_review" =~ ^-?[0-9]+$ ]]; then
            days_to_review=9999
        fi

        if [[ "$days_to_review" -lt 0 ]]; then
            jq -nc \
                --arg pkg "$pkg" \
                --arg review_date "$review_date" \
                --argjson days_to_review "$days_to_review" \
                '{package:$pkg, review_date:$review_date, days_to_review:$days_to_review}' \
                >> "$overdue_temp"
        fi

    done < "$applied_temp"

    local overdue_count=0
    if [[ -s "$overdue_temp" ]]; then
        overdue_count=$(grep -c . "$overdue_temp" || true)
    fi

    echo "Overdue reviews: ${overdue_count}"

    # ============================================
    # STEP 8: Get final held count
    # ============================================
    local final_holds
    final_holds=$(get_current_holds)
    local final_hold_count=0
    if [[ -n "$final_holds" ]]; then
        final_hold_count=$(echo "$final_holds" | grep -c . || true)
    fi

    # ============================================
    # STEP 9: Build arrays and emit JSON
    # ============================================
    local applied_json released_json overdue_json
    applied_json=$( [[ -s "$applied_temp" ]] && jq -s '.' "$applied_temp" || echo '[]' )
    released_json=$( [[ -s "$released_temp" ]] && jq -s '.' "$released_temp" || echo '[]' )
    overdue_json=$( [[ -s "$overdue_temp" ]] && jq -s '.' "$overdue_temp" || echo '[]' )

    jq -n \
        --argjson applied "$applied_json" \
        --argjson released "$released_json" \
        --argjson overdue "$overdue_json" \
        --argjson total_held "$final_hold_count" \
        '{applied: $applied, released: $released, overdue_reviews: $overdue, total_held: $total_held}' \
        > "$OUTPUT_FILE"

    rm -f "$applied_temp" "$released_temp" "$overdue_temp"

    echo "Report saved to: $(basename "$OUTPUT_FILE")"
}

main "$@"
